package com.isea533.mybatis.mapper;

import com.isea533.mybatis.model.UserLoginInfo;
import com.isea533.mybatis.model.UserLoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int countByExample(UserLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int deleteByExample(UserLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int insert(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int insertSelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    List<UserLoginInfo> selectByExample(UserLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    UserLoginInfo selectByPrimaryKey(@Param("id") Integer id, @Param("username") String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserLoginInfo record, @Param("example") UserLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int updateByExample(@Param("record") UserLoginInfo record, @Param("example") UserLoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int updateByPrimaryKeySelective(UserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user login info
     *
     * @mbggenerated Sat Mar 11 00:45:04 CST 2017
     */
    int updateByPrimaryKey(UserLoginInfo record);
}